apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ default "" .Values.namespace }}
  name: {{ include "frontier-squid.fullname" . }}-config
  labels:
    {{- include "frontier-squid.labels" . | nindent 4 }}
data:
  squid.conf: |
{{- $config := "" -}}
{{- if .Values.configFile -}}
{{- $config = .Files.Get .Values.configFile }}
{{- end -}}
{{- if $config -}}
{{ $config | nindent 4 }}
{{- else }}
    # General squid configuration
    # Cache management
    {{- with .Values.config.cache }}
    minimum_object_size {{ default "0 KB" .minSize }}
    cache_dir ufs {{ default "/var/cache/squid" .diskDirectory }} {{ default "10000" .diskSpace }} 16 256
    maximum_object_size {{ default "1 GB" .diskMaxSize }}
    cache_mem {{ default "256 MB" .memorySpace }}
    maximum_object_size_in_memory {{ default "32 KB" .memoryMaxSize }}
    cache_mgr squid
    cache_effective_user squid
    cache_effective_group squid
    memory_cache_shared off
    {{- end }}

    # Logs
    access_log stdio:/dev/stdout rotate=0
    cache_log /var/log/squid/cache.log
    strip_query_terms off

    # Miscellaneous
    mime_table /etc/squid/mime.conf
    icon_directory /usr/share/squid/icons/
    pid_filename /var/run/squid/squid.pid
    max_filedescriptors {{ default "16384" .Values.config.fileDescriptors }}
    http_port 3128
    umask 022
    # As per https://bugs.squid-cache.org/show_bug.cgi?id=4554
    quick_abort_min 0 KB
    quick_abort_max 0 KB
    # As per https://bugs.squid-cache.org/show_bug.cgi?id=4531
    minimum_expiry_time 0
    dns_v4_first on
    negative_ttl 1 minute
    collapsed_forwarding on
    cache_miss_revalidate off
    # Prevent squid PTR lookups (as per http://lists.squid-cache.org/pipermail/squid-users/2016-February/009115.html)
    url_rewrite_extras "%>a %un %>rm myip=%la myport=%lp"
    store_id_extras "%>a %un %>rm myip=%la myport=%lp"
    # Send response header as Apache
    acl apache rep_header Server ^Apache

    # ACL fragments
    # ACL fragment for safe_ports: Will deny not safe_ports
    acl safe_ports port 80
    acl safe_ports port 8000
    
    # ACL fragment for ssl_ports: Will deny connect method for not ssl_ports
    acl CONNECT method connect
    acl ssl_ports port 443
    
    # ACL fragment for stratum_ones
    acl stratum_ones url_regex ^http://cvmfs-stratum-one.cern.ch
    acl stratum_ones url_regex ^http://cernvmfs.gridpp.rl.ac.uk
    acl stratum_ones url_regex ^http://cvmfs-egi.gridpp.rl.ac.uk
    acl stratum_ones url_regex ^http://grid-cvmfs-one.desy.de
    acl stratum_ones url_regex ^http://cvmfs-stratum-one.zeuthen.desy.de
    acl stratum_ones url_regex ^http://klei.nikhef.nl
    acl stratum_ones url_regex ^http://cvmfs01.nikhef.nl
    acl stratum_ones url_regex ^http://cvmfs.fnal.gov
    acl stratum_ones url_regex ^http://cvmfs.racf.bnl.gov
    acl stratum_ones url_regex ^http://hcc-cvmfs.unl.edu
    acl stratum_ones url_regex ^http://cvmfs-s1.*.opensciencegrid.org
    acl stratum_ones url_regex ^http://oasis.opensciencegrid.org
    acl stratum_ones url_regex ^http://cvmfsrepo.lcg.triumf.ca
    acl stratum_ones url_regex ^http://cvmfsrep.grid.sinica.edu.tw
    acl stratum_ones url_regex ^http://cvmfs02.grid.sinica.edu.tw
    acl stratum_ones url_regex ^http://cvmfs-stratum-one.ihep.ac.cn

    # ACL fragment for osgstorage
    acl osgstorage url_regex ^http://osgxroot.usatlas.bnl.gov
    acl osgstorage url_regex ^http://xrd-cache-1.t2.ucsd.edu
    acl osgstorage url_regex ^http://mwt2-stashcache.campuscluster.illinois.edu
    acl osgstorage url_regex ^http://its-condor-xrootd1.syr.edu
    acl osgstorage url_regex ^http://osg-kansas-city-stashcache.nrp.internet2.edu
    acl osgstorage url_regex ^http://fiona.uvalight.net
    acl osgstorage url_regex ^http://osg-chicago-stashcache.nrp.internet2.edu
    acl osgstorage url_regex ^http://osg-new-york-stashcache.nrp.internet2.edu
    acl osgstorage url_regex ^http://sc-cache.chtc.wisc.edu
    acl osgstorage url_regex ^http://osg-gftp.pace.gatech.edu
    
    # ACL fragment for misc
    acl misc url_regex ^http://cernvm-webfs.cern.ch
    acl misc url_regex ^http://hepvm.cern.ch
    acl misc url_regex ^http://sdtcvmfs.cern.ch
    
    # ACL fragment for grid_ca
    acl grid_ca urlpath_regex \.crl$
    acl grid_ca urlpath_regex \.r0$
    acl grid_ca urlpath_regex \.pem$
    acl grid_ca urlpath_regex \.der$
    acl grid_ca urlpath_regex \.crl_url$
    acl grid_ca urlpath_regex \/crls\/
    
    
    # Refresh patterns
    refresh_pattern ^ftp:                1440    20%    10080
    refresh_pattern ^gopher:             1440     0%     1440
    refresh_pattern -i (/cgi-bin/|\?)       0     0%        0
    refresh_pattern .                       0    20%     4320
    
    
    # Allow/Deny Directives
    # Allow directives
    http_access allow localhost
    http_access allow localhost manager
    http_access allow stratum_ones
    http_access allow osgstorage
    http_access allow misc
    http_access allow grid_ca
    
    # Deny directives
    http_access deny !safe_ports
    http_access deny CONNECT !ssl_ports
    http_access deny manager
    http_access deny all
{{- end -}}
