apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontier-squid.fullname" . }}
  labels:
    {{- include "frontier-squid.labels" . | nindent 4 }}
spec: {{- .Values.service | toYaml | trim | nindent 2 }}
  selector:
    {{- include "frontier-squid.selectorLabels" . | nindent 4 }}
