image:
  repository: gitlab-registry.cern.ch/dss/eos/eos-all
  tag: 4.8.78
  pullPolicy: Always

#
# SSS keytab to authenticate against eos mgm
#   The name of the kubernetes secret containing the eos keytab to use.
# Default: eos-sss-keytab
sssKeytab:
  secret:

#
# Prefer colocation with MGM pod
#   Assign weight 100 to colocation with 'component: eos-mgm' as per custom labels.
#   The idea is to re-use the eos container image available on the node running the mgm.
#
podAssignment:
  enableMgmColocation: true
  enableNodeSelector: false     # Requires a node labeled as per customLabels

#
# Custom labels to identify eos-instance-config pod.
#
# They are used by node selection, if enabled (see above).
# Label nodes accordingly to avoid scheduling problems.
#
customLabels:
  service: eos
  component: eos-mgm

#
# The actual EOS MGM configuration
#
config:
  spaceDefault:
    groupSize: 8
    groupMod: 1

  sys:
    recycle: "/eos/user/proc/recycle/"
    versioning: 10

  sysForced:
    blockchecksum: crc32c
    blocksize: 4k
    checksum: adler
    layout: replica
    nstripes: 2
    space: default
    maxsize: "10000000000"

  recycle:
    enable: true
    params:
      size: 10G
      inodes: 10M
      lifetime: "2592000" # 30 days in seconds
      ratio: 0.2

  #
  # OAuth2
  #   Documentation at https://eos-docs.web.cern.ch/using/oauth2.html
  #
  oauth:
    enabled: false
    resourceEndpoint:
    audienceClaim:

  directoryTree:
    create: true
    prefix: "/eos/user"

  demoUsers:
    createUsers: false
    createHomeDirs: true
    quota:
      size: 1T
      inodes: 1M
    userList:
    userBlock:
      howMany: 10
      unamePrefix: "user"
      uidStart: 1000
      gname: "users"
      gid: 100
