apiVersion: v2
#
name: frontier-squid
type: application
version: 0.1.5
appVersion: 4.17-2.1
#
description: Frontier Squid cache for CVMFS clients
icon: https://upload.wikimedia.org/wikipedia/fr/b/b7/Squid-cache_logo.jpg
keywords:
  - Frontier
  - Squid
  - Cache
  - CVMFS
  - ScienceBox
home: http://frontier.cern.ch/
sources:
  - http://frontier.cern.ch/
  - https://twiki.cern.ch/twiki/bin/view/Frontier/InstallSquid
  - https://gitlab.cern.ch/sciencebox
