apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.authprovidermachine.cfgmapName }}
  labels:
    {{- include "revad.labels" . | nindent 4 }}
data:
  revad.toml: |-
    [shared]
    gatewaysvc = "localhost:9142"
    jwt_secret = "POZSOrlP7AgnTxH7MJebWV8ohvsApgbd4u3Joen30c"

    [grpc]
    address = "0.0.0.0:9166"

    [grpc.services.authprovider]
    auth_manager = "machine"

    [grpc.services.authprovider.auth_managers.machine]
    api_key = "random_api_key"
    gateway_addr = "{{ .Release.Name }}-gateway:9142"
