apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.cfgmapName }}
  labels:
    {{- include "revad.labels" . | nindent 4 }}
data:
  revad.toml: |-
    [shared]
    gatewaysvc = "localhost:9142"
    jwt_secret = "POZSOrlP7AgnTxH7MJebWV8ohvsApgbd4u3Joen30c"

    [grpc]
    address = "0.0.0.0:9142"

    [grpc.services.gateway]
    commit_share_to_storage_grant = true
    commit_share_to_storage_ref = true
    disable_home_creation_on_login = false
    transfer_shared_secret = "replace-me-with-a-transfer-secret"
    transfer_expires = 86400
    share_folder = "MyShares"
    usershareprovidersvc = "localhost:9142"
    publicshareprovidersvc = "localhost:9142"


    datagateway = "http://localhost:9143/data"

    [grpc.services.authprovider]
    auth_manager = "ldap"

    [grpc.services.authprovider.auth_managers.ldap]
    hostname = "sciencebox-ldap"
    port = 636
    insecure = true
    base_dn = "dc=owncloud,dc=com"
    loginfilter = "(&(objectclass=inetOrgPerson)(objectclass=owncloud)(|(uid={{`{{login}}`}})(mail={{`{{login}}`}})))"
    bind_username = "cn=readuser,dc=owncloud,dc=com"
    bind_password = "readuser"
    schema = { dn = "dn", uid = "cn", mail = "mail", displayName = "displayname", cn = "cn" }
    gatewaysvc = "localhost:9142"

    [grpc.services.authregistry]
    driver = "static"

    [grpc.services.authregistry.drivers.static.rules]
    basic = "localhost:9142"
    publicshares = "sciencebox-storageprovider-public:9278"
    machine = "sciencebox-authprovider-machine:9166"
    bearer = "sciencebox-authprovider-bearer:9158"

    [grpc.services.userprovider]
    driver = "ldap"

    [grpc.services.userprovider.drivers.ldap]
    hostname="sciencebox-ldap"
    port = 636
    insecure = true
    base_dn = "dc=owncloud,dc=com"
    userfilter="(&(objectclass=owncloud)(cn=%s))"
    findfilter="(&(objectclass=owncloud)(|(uid={{`{{query}}`}}*)(cn={{`{{query}}`}}*)(displayname={{`{{query}}`}}*)(mail={{`{{query}}`}}*)(description={{`{{query}}`}}*)))"
    attributefilter="(&(objectclass=owncloud)({{`{{attr}}`}}={{`{{value}}`}}))"
    groupfilter="(objectclass=owncloud)"
    bind_username = "cn=readuser,dc=owncloud,dc=com"
    bind_password = "readuser"

    [grpc.services.userprovider.drivers.ldap.schema]
    uid="uid"
    displayName="displayName"
    dn="dn"
    cn="cn"
    mail="mail"

    [grpc.services.groupprovider]
    driver = "ldap"

    [grpc.services.groupprovider.drivers.ldap]
    hostname="sciencebox-ldap"
    port = 636
    insecure = true
    base_dn = "dc=owncloud,dc=com"
    groupfilter="(objectclass=owncloud)"
    findfilter="(&(objectclass=posixGroup)(|(cn={{`{{query}}`}}*)(displayname={{`{{query}}`}}*)(mail={{`{{query}}`}}*)))"
    attributefilter="(&(objectclass=posixGroup)({{`{{attr}}`}}={{`{{value}}`}}))"
    memberfilter="(&(objectclass=posixAccount)(cn={{`{{.OpaqueId}}`}}))"
    bind_username = "cn=readuser,dc=owncloud,dc=com"
    # needs to be templated (for local dev purposes, idp should be ${HOSTNAME})
    bind_password = "readuser"

    [grpc.services.groupprovider.drivers.ldap.schema]
    gid="cn"
    displayName="cn"
    dn="dn"
    cn="cn"

    [grpc.services.storageregistry]
    driver = "static"

    [grpc.services.storageregistry.drivers.static]
    home_provider = "/home"

    [grpc.services.storageregistry.drivers.static.rules]
    "/home" = { address = "sciencebox-storageprovider-home:18000" }
    "/eos/user" = { address = "sciencebox-storageprovider-user:16000" }
    "eos" = { address = "sciencebox-storageprovider-user:16000" }
    "/public" = { address = "sciencebox-storageprovider-public:9278" }
    "public-storage" = { address = "sciencebox-storageprovider-public:9278" }

    [grpc.services.publicshareprovider]
    driver = "sql"
    allowed_paths_for_shares = ["^/eos/user/[a-z]/[0-9a-z\\-]+/.+", "^/eos/project/[a-z]/[0-9a-z\\-]+/.+"]

    [grpc.services.publicshareprovider.drivers.sql]
    db_username = "root"
    db_password = "reva"
    db_host = "sciencebox-mariadb"
    db_port = 3306
    db_name = "my_database"
    password_hash_cost = 11
    enable_expired_shares_cleanup = false
    janitor_run_interval = 60

    [grpc.services.usershareprovider]
    driver = "sql"
    allowed_paths_for_shares = ["^/eos/user/[a-z]/[0-9a-z\\-]+/.+", "^/eos/project/[a-z]/[0-9a-z\\-]+/.+"]

    [grpc.services.usershareprovider.drivers.sql]
    db_username = "root"
    db_password = "reva"
    db_host = "sciencebox-mariadb"
    db_port = 3306
    db_name = "my_database"
    password_hash_cost = 11
    enable_expired_shares_cleanup = false
    janitor_run_interval = 60

    [http]
    address = "0.0.0.0:9143"

    [http.services.datagateway]
    transfer_shared_secret = "replace-me-with-a-transfer-secret"
    timeout = 86400
    insecure = true
    prefix = "data"

    [http.services.ocdav]
    files_namespace = "/eos/{{`{{substr 0 1 .Username}}`}}"
    timeout = 86400
    insecure = true

    [http.services.ocs]
    share_prefix = "/"
    home_namespace = "/"

    [http.services.ocs.config]
    version = "1.8"
    website = "reva"
    # needs to templated
    # host = "https://jimil-nuc.dyndns.cern.ch"
    contact = "admin@localhost"
    ssl = "false"

    [http.services.ocs.capabilities.capabilities.core]
    poll_interval = 60
    webdav_root = "remote.php/webdav"
    status = { installed = true, maintenance = false, nwwsaDbUpgrade = false, version = "10.0.11.5", versionstring = "10.0.11", edition = "community", productname = "reva", hostname = "" }
    support_url_signing = false

    [http.services.ocs.capabilities.capabilities.checksums]
    supported_types = ["sha1", "md5", "adler32"]

    [http.services.ocs.capabilities.capabilities.files]
    private_links = false
    bigfilechunking = false
    blacklisted_files = []
    undelete = true
    versioning = false
    favorites = true

    [http.services.ocs.capabilities.capabilities.dav]

    [http.services.ocs.capabilities.capabilities.files_sharing]
    api_enabled = true
    resharing = false
    group_sharing = true
    auto_accept_share = true
    share_with_group_members_only = true
    share_with_membership_groups_only = true
    default_permissions = 22
    search_min_length = 3

    [http.services.ocs.capabilities.capabilities.files_sharing.public]
    enabled = true
    send_mail = true
    social_share = true
    upload = true
    multiple = true
    supports_upload_only = true
    password = { enforced = false, enforced_for = { read_only = false, read_write = false, upload_only = false } }
    expire_date = { enabled = true }
    can_edit = true

    [http.services.ocs.capabilities.capabilities.files_sharing.user]
    send_mail = true
    profile_picture = false
    settings = [{ enabled = true, version = "1.0.0" }]

    [http.services.ocs.capabilities.capabilities.files_sharing.user_enumeration]
    enabled = true
    group_members_only = true