apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.storageproviderpublic.cfgmapName }}
  labels:
    {{- include "revad.labels" . | nindent 4 }}
data:
  revad.toml: |-
    [shared]
    gatewaysvc = "{{ .Release.Name }}-gateway:9142"
    jwt_secret = "POZSOrlP7AgnTxH7MJebWV8ohvsApgbd4u3Joen30c"

    [grpc]
    address = "0.0.0.0:9278"

    [grpc.services.publicstorageprovider]
    mount_path = "/public"
    mount_id = "public-storage"
    gateway_addr = "{{ .Release.Name }}-gateway:9142"

    [grpc.services.authprovider]
    auth_manager = "publicshares"

    [grpc.services.authprovider.auth_managers.publicshares]
    gateway_addr = "{{ .Release.Name }}-gateway:9142"
