apiVersion: v1
kind: ConfigMap
metadata:
  name: cernbox-web-init
data:
  cbox_init.sh: |
    #!/bin/bash
    set -x

    wget -O /var/www/web/web-tar.gz $WEB_ASSET
    tar -xf /var/www/web/web-tar.gz -C /var/www/web/
    rm -r /var/www/web/web-tar.gz

    wget -O /var/www/web/theme-cernbox.tar.gz $WEB_THEME
    tar -xf /var/www/web/theme-cernbox.tar.gz -C /var/www/web/
    rm -f /var/www/web/theme-cernbox.tar.gz

    mkdir -p /var/www/web/cernbox/theme-cernbox/
    mv /var/www/web/assets /var/www/web/cernbox/theme-cernbox/assets
