apiVersion: v2
#
name: cernbox
type: application
version: 0.0.1
appVersion: 1.3.3
#
description: The chart to deploy and configure CERNBox in ScienceBox
icon: https://avatars.githubusercontent.com/u/5640319
#
dependencies:
- name: revad
  version: "1.4.1"
  alias: gateway
  repository: "file://../../revad-fork/revad"

- name: revad
  version: "1.4.1"
<<<<<<< HEAD
  alias: storageprovider-home
=======
  alias: storageproviderhome
>>>>>>> 970822375819c1c093baa6e053630ccf15543382
  repository: "file://../../revad-fork/revad"

- name: revad
  version: "1.4.1"
<<<<<<< HEAD
  alias: storageprovider-user
=======
  alias: storageprovideruser
>>>>>>> 970822375819c1c093baa6e053630ccf15543382
  repository: "file://../../revad-fork/revad"

- name: revad
  version: "1.4.1"
<<<<<<< HEAD
  alias: storageprovider-public
=======
  alias: storageproviderpublic
>>>>>>> 970822375819c1c093baa6e053630ccf15543382
  repository: "file://../../revad-fork/revad"

- name: revad
  version: "1.4.1"
<<<<<<< HEAD
  alias: authprovider-machine
=======
  alias: authprovidermachine
>>>>>>> 970822375819c1c093baa6e053630ccf15543382
  repository: "file://../../revad-fork/revad"

- name: revad
  version: "1.4.1"
<<<<<<< HEAD
  alias: authprovider-bearer
=======
  alias: authproviderbearer
>>>>>>> 970822375819c1c093baa6e053630ccf15543382
  repository: "file://../../revad-fork/revad"

- name: ocis
  version: 0.0.7
  repository: "https://registry.cern.ch/chartrepo/sciencebox"

- name: nginx
  alias: cernbox-web
  version: 13.0.0
  repository: "https://charts.bitnami.com/bitnami"
