{{- if .Values.ingress.enabled }}
{{- range $service, $ingress := .Values.ingress.services }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "revad.fullname" $ }}-{{ $service }}
  labels: {{- include "revad.labels" $ | nindent 4 }}
  annotations:
    {{- if $ingress.annotations }}
{{ toYaml $ingress.annotations | indent 4 }}
    {{- end }}
spec:
  rules:
    {{- if $ingress.hostname }}
    - host: {{ $ingress.hostname }}
      http:
        paths:
          - path: {{ $ingress.path }}
            backend:
              service:
                name: {{ template "revad.fullname" $ }}
                port:
                  name: {{ $service }}
            pathType: ImplementationSpecific
    {{- end }}
  {{- if $ingress.tls }}
  tls:
{{ toYaml $ingress.tls | indent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
