apiVersion: v1
kind: Service
metadata:
  name: {{ include "revad.fullname" . }}
  labels:
    {{- include "revad.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.http }}
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
    {{- if .Values.service.grpc }}
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end }}
  selector:
    {{- include "revad.selectorLabels" . | nindent 4 }}
