apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  config.json: |-
    {
      "server": "https://jimil-laptop.dyndns.cern.ch/",
      "version": "0.1.0",
      "openIdConnect": {
        "metadata_url": "https://jimil-laptop.dyndns.cern.ch/.well-known/openid-configuration",
        "authority": "https://jimil-laptop.dyndns.cern.ch/",
        "client_id": "web",
        "response_type": "code",
        "scope": "openid profile email"
      },
      "apps": ["files"],
      "external_apps": [
      ],
      "options": {
        "hideSearchBar": true,
        "homeFolder": "{{ printf "/eos/user/{{substr 0 1 .Id}}/{{.Id}}" }}"
      }
    }