apiVersion: v2
#
name: sciencebox
type: application
version: 0.0.3
#
description: The chart to deploy and configure ScienceBox
icon: #TODO
#
dependencies:
#
# User account info
- name: openldap
  alias: ldap
  version: 2.0.4
  repository: "https://jp-gouin.github.io/helm-openldap/"
- name: ldap-instance-config
  version: 0.0.1
  repository: "https://registry.cern.ch/chartrepo/sciencebox"
#
# CBox shares
- name: mariadb
  version: 11.0.2
  repository: "https://charts.bitnami.com/bitnami"
#
# ScienceBox welcome page
- name: nginx
  alias: nginx-welcome-page
  version: 13.0.0
  repository: "https://charts.bitnami.com/bitnami"
#
# EOS
- name: server
  alias: eos
  version: 0.1.3
  repository: "https://registry.cern.ch/chartrepo/eos"
- name: eos-instance-config
  version: 0.0.5
  repository: "https://registry.cern.ch/chartrepo/sciencebox"
#
# SWAN
- name: swan
  version: 0.1.10
  repository: "https://registry.cern.ch/chartrepo/swan"
#
# CERNBox
- name: revad
  version: "1.3.3"
  alias: gateway
  repository: "https://cs3org.github.io/charts"

- name: revad
  version: "1.3.3"
  alias: storageprovider-home
  repository: "https://cs3org.github.io/charts"

- name: revad
  version: "1.3.3"
  alias: storageprovider-user
  repository: "https://cs3org.github.io/charts"

- name: revad
  version: "1.3.3"
  alias: storageprovider-public
  repository: "https://cs3org.github.io/charts"

- name: revad
  version: "1.3.3"
  alias: authprovider-machine
  repository: "https://cs3org.github.io/charts"

- name: revad
  version: "1.3.3"
  alias: authprovider-bearer
  repository: "https://cs3org.github.io/charts"

- name: ocis
  version: 0.0.6
  repository: "https://registry.cern.ch/chartrepo/sciencebox"

- name: nginx
  alias: cernbox-web
  version: 13.0.0
  repository: "https://charts.bitnami.com/bitnami"

